///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Nespresso_Web_App
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Nespresso_Web_AppRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f5f247d4-8d09-4a8b-a703-782f7aa1986b")]
    public partial class Nespresso_Web_AppRepository : RepoGenBaseFolder
    {
        static Nespresso_Web_AppRepository instance = new Nespresso_Web_AppRepository();
        Nespresso_Web_AppRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the Nespresso_Web_AppRepository element repository.
        /// </summary>
        [RepositoryFolder("f5f247d4-8d09-4a8b-a703-782f7aa1986b")]
        public static Nespresso_Web_AppRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Nespresso_Web_AppRepository() 
            : base("Nespresso_Web_AppRepository", "/", null, 0, false, "f5f247d4-8d09-4a8b-a703-782f7aa1986b", ".\\RepositoryImages\\Nespresso_Web_AppRepositoryf5f247d4.rximgres")
        {
            _applicationundertest = new Nespresso_Web_AppRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f5f247d4-8d09-4a8b-a703-782f7aa1986b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("5710b1e2-a750-43d3-bc66-6caa5e1fd233")]
        public virtual Nespresso_Web_AppRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Nespresso_Web_AppRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("5710b1e2-a750-43d3-bc66-6caa5e1fd233")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            Nespresso_Web_AppRepositoryFolders.HeaderFolder _header;
            RepoItemInfo _addtobagbuttonsmalliconsignglyphglyInfo;
            RepoItemInfo _spantag20Info;
            RepoItemInfo _taminibasketopenInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.nespresso.com']", parentFolder, 30000, null, false, "5710b1e2-a750-43d3-bc66-6caa5e1fd233", "")
            {
                _header = new Nespresso_Web_AppRepositoryFolders.HeaderFolder(this);
                _addtobagbuttonsmalliconsignglyphglyInfo = new RepoItemInfo(this, "AddToBagButtonSmallIconSignGlyphGly", ".//section[#'special-reserve-edition-exclusive-original']/div[2]/article[1]/div//button/?/?/i", "", 30000, null, "257a69e5-2ee6-4472-a958-a6826df8cd93");
                _spantag20Info = new RepoItemInfo(this, "SpanTag20", ".//div[#'QuantitySelector__wrapper']//ul/li[3]/button/span[@innertext='20']", "", 30000, null, "dcdfdaed-8bb9-492f-ba7a-27069deda156");
                _taminibasketopenInfo = new RepoItemInfo(this, "TaMiniBasketOpen", ".//button[#'ta-mini-basket__open']", "", 30000, null, "3b2705cc-29a5-4ea8-901f-6a04e4d6c6e7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5710b1e2-a750-43d3-bc66-6caa5e1fd233")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5710b1e2-a750-43d3-bc66-6caa5e1fd233")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddToBagButtonSmallIconSignGlyphGly item.
            /// </summary>
            [RepositoryItem("257a69e5-2ee6-4472-a958-a6826df8cd93")]
            public virtual Ranorex.ITag AddToBagButtonSmallIconSignGlyphGly
            {
                get
                {
                    return _addtobagbuttonsmalliconsignglyphglyInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The AddToBagButtonSmallIconSignGlyphGly item info.
            /// </summary>
            [RepositoryItemInfo("257a69e5-2ee6-4472-a958-a6826df8cd93")]
            public virtual RepoItemInfo AddToBagButtonSmallIconSignGlyphGlyInfo
            {
                get
                {
                    return _addtobagbuttonsmalliconsignglyphglyInfo;
                }
            }

            /// <summary>
            /// The SpanTag20 item.
            /// </summary>
            [RepositoryItem("dcdfdaed-8bb9-492f-ba7a-27069deda156")]
            public virtual Ranorex.SpanTag SpanTag20
            {
                get
                {
                    return _spantag20Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTag20 item info.
            /// </summary>
            [RepositoryItemInfo("dcdfdaed-8bb9-492f-ba7a-27069deda156")]
            public virtual RepoItemInfo SpanTag20Info
            {
                get
                {
                    return _spantag20Info;
                }
            }

            /// <summary>
            /// The TaMiniBasketOpen item.
            /// </summary>
            [RepositoryItem("3b2705cc-29a5-4ea8-901f-6a04e4d6c6e7")]
            public virtual Ranorex.ButtonTag TaMiniBasketOpen
            {
                get
                {
                    return _taminibasketopenInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The TaMiniBasketOpen item info.
            /// </summary>
            [RepositoryItemInfo("3b2705cc-29a5-4ea8-901f-6a04e4d6c6e7")]
            public virtual RepoItemInfo TaMiniBasketOpenInfo
            {
                get
                {
                    return _taminibasketopenInfo;
                }
            }

            /// <summary>
            /// The Header folder.
            /// </summary>
            [RepositoryFolder("e7e0e21a-fa70-4a81-a329-acf476784663")]
            public virtual Nespresso_Web_AppRepositoryFolders.HeaderFolder Header
            {
                get { return _header; }
            }
        }

        /// <summary>
        /// The HeaderFolder folder.
        /// </summary>
        [RepositoryFolder("e7e0e21a-fa70-4a81-a329-acf476784663")]
        public partial class HeaderFolder : RepoGenBaseFolder
        {
            RepoItemInfo _headernavigationbaritemiconspriteInfo;
            RepoItemInfo _strongtag3000Info;
            RepoItemInfo _jamaicabluemountainInfo;

            /// <summary>
            /// Creates a new Header  folder.
            /// </summary>
            public HeaderFolder(RepoGenBaseFolder parentFolder) :
                    base("Header", ".//div[#'header']", parentFolder, 30000, null, false, "e7e0e21a-fa70-4a81-a329-acf476784663", "")
            {
                _headernavigationbaritemiconspriteInfo = new RepoItemInfo(this, "HeaderNavigationBarItemIconSprite", ".//nav/ul/li[1]/a/div/span", "", 30000, null, "c3932aca-78b8-4c52-a866-fd13038e80ec");
                _strongtag3000Info = new RepoItemInfo(this, "StrongTag3000", "div[2]/div/div/div/div/div/div[4]/div/div/div/div[2]/?/?/table/tbody/tr[2]/td[1]/span[2]/strong[@innertext='30,00€']", "", 30000, null, "8263b7cd-f389-45fc-bab1-26bffa5a669c");
                _jamaicabluemountainInfo = new RepoItemInfo(this, "JamaicaBlueMountain", "div[2]/div/div/div/div/div/div[4]/div/div/div/div[2]/?/?/table/tbody/tr[2]/td[1]/span[@innertext='Jamaica Blue Mountain']", "", 30000, null, "b6a9e6d4-3b72-4e3a-ab75-e84bd0b3b343");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e7e0e21a-fa70-4a81-a329-acf476784663")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e7e0e21a-fa70-4a81-a329-acf476784663")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HeaderNavigationBarItemIconSprite item.
            /// </summary>
            [RepositoryItem("c3932aca-78b8-4c52-a866-fd13038e80ec")]
            public virtual Ranorex.SpanTag HeaderNavigationBarItemIconSprite
            {
                get
                {
                    return _headernavigationbaritemiconspriteInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The HeaderNavigationBarItemIconSprite item info.
            /// </summary>
            [RepositoryItemInfo("c3932aca-78b8-4c52-a866-fd13038e80ec")]
            public virtual RepoItemInfo HeaderNavigationBarItemIconSpriteInfo
            {
                get
                {
                    return _headernavigationbaritemiconspriteInfo;
                }
            }

            /// <summary>
            /// The StrongTag3000 item.
            /// </summary>
            [RepositoryItem("8263b7cd-f389-45fc-bab1-26bffa5a669c")]
            public virtual Ranorex.StrongTag StrongTag3000
            {
                get
                {
                    return _strongtag3000Info.CreateAdapter<Ranorex.StrongTag>(true);
                }
            }

            /// <summary>
            /// The StrongTag3000 item info.
            /// </summary>
            [RepositoryItemInfo("8263b7cd-f389-45fc-bab1-26bffa5a669c")]
            public virtual RepoItemInfo StrongTag3000Info
            {
                get
                {
                    return _strongtag3000Info;
                }
            }

            /// <summary>
            /// The JamaicaBlueMountain item.
            /// </summary>
            [RepositoryItem("b6a9e6d4-3b72-4e3a-ab75-e84bd0b3b343")]
            public virtual Ranorex.SpanTag JamaicaBlueMountain
            {
                get
                {
                    return _jamaicabluemountainInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The JamaicaBlueMountain item info.
            /// </summary>
            [RepositoryItemInfo("b6a9e6d4-3b72-4e3a-ab75-e84bd0b3b343")]
            public virtual RepoItemInfo JamaicaBlueMountainInfo
            {
                get
                {
                    return _jamaicabluemountainInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
