///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Nespresso_Web_App
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("1a21e077-90ef-4e96-a2f4-88cfb259499b", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Nespresso_Web_AppRepository repository.
        /// </summary>
        public static Nespresso_Web_AppRepository repo = Nespresso_Web_AppRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Header.HeaderNavigationBarItemIconSprite' at 31;25.", repo.ApplicationUnderTest.Header.HeaderNavigationBarItemIconSpriteInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Header.HeaderNavigationBarItemIconSprite.Click("31;25");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.AddToBagButtonSmallIconSignGlyphGly' at 16;20.", repo.ApplicationUnderTest.AddToBagButtonSmallIconSignGlyphGlyInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.AddToBagButtonSmallIconSignGlyphGly.Click("16;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SpanTag20' at 11;9.", repo.ApplicationUnderTest.SpanTag20Info, new RecordItemIndex(2));
            repo.ApplicationUnderTest.SpanTag20.Click("11;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.TaMiniBasketOpen' at 132;27.", repo.ApplicationUnderTest.TaMiniBasketOpenInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.TaMiniBasketOpen.Click("132;27");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'ApplicationUnderTest.Header.JamaicaBlueMountain'", repo.ApplicationUnderTest.Header.JamaicaBlueMountainInfo, new ActionTimeout(5000), new RecordItemIndex(4));
            repo.ApplicationUnderTest.Header.JamaicaBlueMountainInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Jamaica Blue Mountain') on item 'ApplicationUnderTest.Header.JamaicaBlueMountain'.", repo.ApplicationUnderTest.Header.JamaicaBlueMountainInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ApplicationUnderTest.Header.JamaicaBlueMountainInfo, "InnerText", "Jamaica Blue Mountain");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='30,00€') on item 'ApplicationUnderTest.Header.StrongTag3000'.", repo.ApplicationUnderTest.Header.StrongTag3000Info, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.ApplicationUnderTest.Header.StrongTag3000Info, "InnerText", "30,00€");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
